/**
 * Base de conhecimento do sistema (all4pay IA) — o que o assistente "entende"
 * sobre as FUNCIONALIDADES e os CÁLCULOS do all4pay. Responde a perguntas
 * conceituais ("o que é runway?", "como calcula o EBITDA?", "para que serve a
 * conciliação?") na hora, sem depender de chave de IA, e aponta a tela onde o
 * tema vive. Combina com a memória adaptativa (assistant-memory) para aprender
 * quais temas o cliente mais pergunta. Determinístico, demo-safe.
 */
export interface KBEntry {
  id: string;
  termos: RegExp; // gatilhos (sinônimos pt-BR)
  titulo: string;
  texto: string; // explicação + fórmula quando há
  rota?: string; // onde abrir
}

export const KB: KBEntry[] = [
  { id: "runway", termos: /runway|f[oô]lego|quantos meses.*caixa|dura(r)? o caixa/, titulo: "Runway de caixa", texto: "Por quantos meses o caixa atual cobre o ritmo de queima. Fórmula: saldo disponível ÷ burn mensal. Cai quando o burn sobe ou o saldo encolhe.", rota: "/fluxo-caixa" },
  { id: "burn-multiple", termos: /burn multiple|múltiplo de queima|efici[êe]ncia de queima|quanto queimo (para|pra) crescer/, titulo: "Burn multiple", texto: "Quanto de caixa você queima para cada R$1 de nova receita (queima líquida ÷ crescimento de receita). Abaixo de 1 é eficiente; muito acima indica crescimento caro.", rota: "/inteligencia" },
  { id: "burn", termos: /burn|queima de caixa|consumo de caixa/, titulo: "Burn rate", texto: "Quanto de caixa a operação consome por mês, em média (saídas − entradas recorrentes). É o denominador do runway.", rota: "/inteligencia" },
  { id: "ltvcac", termos: /ltv\s*\/?\s*cac|rela[çc][ãa]o ltv/, titulo: "LTV / CAC", texto: "Razão LTV ÷ CAC. Acima de 3× costuma indicar aquisição saudável; abaixo de 1× você gasta mais para adquirir do que o cliente retorna.", rota: "/painel-vendas" },
  { id: "ltv", termos: /\bltv\b|lifetime value|valor do cliente/, titulo: "LTV", texto: "Valor que um cliente gera ao longo de TODO o relacionamento (não de um só período) — idealmente pela margem, não pela receita bruta. Estimativa: ticket médio × margem × tempo de permanência. Aqui usamos uma proxy simples do período (receita ÷ clientes distintos). Quanto maior, mais valioso é cada cliente adquirido.", rota: "/painel-vendas" },
  { id: "cac", termos: /\bcac\b|custo de aquisi|custo por cliente/, titulo: "CAC", texto: "Custo de Aquisição de Cliente: gasto de marketing ÷ clientes adquiridos no período. Mede quanto custa trazer um novo cliente.", rota: "/painel-vendas" },
  { id: "ebitda", termos: /ebitda/, titulo: "EBITDA", texto: "Resultado operacional antes de juros, impostos sobre o lucro, depreciação e amortização. Aqui: receita − despesas operacionais (exclui financeiro, D&A e IRPJ/CSLL). % Receita = EBITDA ÷ receita.", rota: "/painel-vendas" },
  { id: "mc", termos: /margem de contribui|margem contribui/, titulo: "Margem de contribuição", texto: "Receita − custos variáveis (CMV, comissões, taxas de gateway, frete). É o que sobra de cada venda para cobrir os custos fixos e gerar lucro.", rota: "/dre" },
  { id: "faturamento", termos: /faturamento|receita bruta/, titulo: "Faturamento bruto", texto: "Soma de todas as entradas (vendas/serviços) reconhecidas no período pela competência (data de vencimento/emissão).", rota: "/painel-vendas" },
  { id: "dre", termos: /\bdre\b|demonstra[çc][ãa]o de resultado|resultado do exerc/, titulo: "DRE", texto: "Demonstração do Resultado: cascata de Receita → impostos → líquida → CMV → lucro bruto → despesas → EBITDA → financeiro → lucro líquido, com drill-down por categoria.", rota: "/dre" },
  { id: "fcf", termos: /fluxo de caixa livre|free cash flow|\bfcf\b|caixa livre/, titulo: "Fluxo de caixa livre (FCF)", texto: "O caixa que sobra da operação depois de cobrir custos e investimentos — o dinheiro realmente disponível para reservar, distribuir ou reinvestir. É a base do runway.", rota: "/fluxo-caixa" },
  { id: "fluxo", termos: /fluxo de caixa|entradas e sa[íi]das|cash ?flow/, titulo: "Fluxo de caixa", texto: "Entradas − saídas ao longo do tempo (regime de caixa), com saldo acumulado, projeção e cenários. Diferente do DRE (competência).", rota: "/fluxo-caixa" },
  { id: "inadimplencia", termos: /inadimpl[êe]ncia|atraso|cliente de risco|vai pagar/, titulo: "Inadimplência (risco de crédito)", texto: "Prevê o risco de calote ANTES de acontecer, pelo comportamento de pagamento de cada cliente (atraso médio, tendência, oscilação). Devolve score + fatores explicáveis + ação de cobrança.", rota: "/inadimplencia" },
  { id: "concil-auto", termos: /concilia[çc][ãa]o autom[áa]tica|matching autom|bate autom/, titulo: "Conciliação automática", texto: "O sistema casa cada linha do extrato com o título correspondente por valor+data+documento (matching probabilístico); só o que fica em dúvida vai para revisão manual.", rota: "/conciliacao-bancaria" },
  { id: "conciliacao", termos: /concilia[çc][ãa]o|ofx|bater extrato|extrato banc/, titulo: "Conciliação bancária", texto: "Compara o que está lançado no all4pay com o extrato do banco (OFX) e sinaliza o que bate/não bate. Garante que o saldo do sistema = saldo real.", rota: "/conciliacao-bancaria" },
  { id: "mrr", termos: /\bmrr\b|recorr[êe]ncia|assinatura|receita recorrente/, titulo: "Recorrências / MRR", texto: "Receita recorrente mensal de contratos/assinaturas. Cada recorrência projeta as próximas faturas como entradas previstas no fluxo.", rota: "/recorrencias" },
  { id: "score", termos: /score|sa[úu]de financeira|nota da empresa/, titulo: "Score de saúde financeira", texto: "Nota 0–100 ponderando liquidez, runway, inadimplência, margem, volatilidade, concentração e crescimento. Acompanha a tendência e a probabilidade de ruptura de caixa.", rota: "/inteligencia" },
  { id: "chargeback", termos: /chargeback|contesta[çc][ãa]o/, titulo: "Chargeback", texto: "Estorno forçado de uma cobrança no cartão, contestada pelo portador. Reduz o faturamento líquido e é monitorado no painel de Vendas.", rota: "/painel-vendas" },
  { id: "reembolso", termos: /reembolso|devolu[çc][ãa]o de venda/, titulo: "Reembolso", texto: "Devolução de um valor ao cliente (estorno voluntário). Abate da receita no período em que ocorre.", rota: "/painel-vendas" },
  { id: "regime", termos: /compet[êe]ncia|regime de caixa|regime cont[áa]bil|caixa vs compet/, titulo: "Competência × Caixa", texto: "São duas datas do mesmo lançamento: competência (quando o fato aconteceu → vai pro DRE) e caixa (quando o dinheiro entra/sai → vai pro fluxo). O DRE usa competência; o fluxo de caixa usa caixa.", rota: "/dre" },
  { id: "aging", termos: /aging|envelhecimento|faixa de atraso|dias de atraso/, titulo: "Aging (envelhecimento)", texto: "Agrupa os títulos em aberto por faixa de atraso (a vencer, 1–30, 31–60, 60+ dias). Mostra o quão velha é a dívida de cada cliente — quanto mais velho, mais difícil receber.", rota: "/inadimplencia" },
  { id: "rateio", termos: /rateio|centro de custo|ratear|por projeto/, titulo: "Rateio / Centro de custo", texto: "Distribui um lançamento entre projetos ou centros de custo, para saber quanto cada área gastou/gerou. Alimenta o DRE por centro de custo.", rota: "/centros-custo" },
  { id: "liquidez", termos: /liquidez corrente|[íi]ndice de liquidez/, titulo: "Liquidez corrente", texto: "Mede se os recursos de curto prazo cobrem as obrigações de curto prazo. Fórmula: ativo circulante ÷ passivo circulante. Acima de 1 indica folga para honrar as contas.", rota: "/inteligencia" },
  { id: "concentracao", termos: /concentra[çc][ãa]o|depend[êe]ncia de cliente|hhi/, titulo: "Concentração de receita", texto: "O quanto sua receita depende de poucos clientes. Medida pelo índice HHI e pelo peso do maior cliente — concentração alta é risco se um deles sair.", rota: "/risco" },
  { id: "capital-giro", termos: /capital de giro|giro|necessidade de capital/, titulo: "Capital de giro", texto: "O dinheiro que a operação precisa para girar entre pagar fornecedores e receber dos clientes. Quanto maior o descasamento de prazos, mais capital de giro é exigido.", rota: "/fluxo-caixa" },
  { id: "churn", termos: /churn|cancelamento|perda de clientes/, titulo: "Churn", texto: "A taxa de cancelamento de assinaturas/recorrências no período. Churn alto derruba o MRR — receita recorrente que você deixa de ter nos próximos meses.", rota: "/recorrencias" },
  { id: "nsu", termos: /\bnsu\b|autoriza[çc][ãa]o|c[óo]digo da transa/, titulo: "NSU", texto: "Número que identifica uma transação de cartão junto à adquirente. Serve para conciliar cada venda com o repasse que cai na conta.", rota: "/conciliacao-bancaria" },
  { id: "boleto", termos: /boleto|linha digit|c[óo]digo de barras/, titulo: "Boleto", texto: "Título de cobrança bancária com vencimento e linha digitável. Vira um recebível previsto no fluxo até ser pago/baixado.", rota: "/boletos" },
  { id: "pix", termos: /\bpix\b|chave pix/, titulo: "Pix", texto: "Pagamento/recebimento instantâneo. Entra como lançamento imediato (data de caixa = data de vencimento), sem prazo de compensação.", rota: "/recebimentos" },
  { id: "nfse", termos: /nfs-?e|nota fiscal|nota de servi[çc]|emitir nota/, titulo: "Nota fiscal / NFS-e", texto: "Documento fiscal da venda ou serviço. A venda é o documento-mãe que propaga para recebível, imposto e nota.", rota: "/notas-fiscais" },
  { id: "breakeven", termos: /ponto de equil[íi]brio|break[ -]?even|equil[íi]brio/, titulo: "Ponto de equilíbrio", texto: "O faturamento mínimo para as receitas cobrirem todos os custos (resultado zero). Abaixo dele, a operação fica no vermelho.", rota: "/dre" },
  { id: "prev-real", termos: /previsto (vs|x|e|contra) realizado|realizado (vs|x) previsto|acur[áa]cia/, titulo: "Previsto × Realizado", texto: "Compara o que estava planejado (previsto/agendado) com o que de fato aconteceu (realizado), medindo a acurácia do seu planejamento.", rota: "/fluxo-caixa" },
  { id: "partidas", termos: /partidas? (dobrada|dupla)|dupla partida|d[ée]bito e cr[ée]dito|raz[ãa]o|ledger/, titulo: "Partidas dobradas (razão)", texto: "Todo lançamento afeta duas contas: um débito e um crédito de igual valor. Garante que o balanço sempre fecha (débitos = créditos).", rota: "/razao" },
  { id: "provisao", termos: /provis[ãa]o|provisionament|accrual|compet[êe]ncia futura|despesa (a )?apropriar/, titulo: "Provisão / Accrual", texto: "Reconhece uma despesa/receita no período em que ela ocorre (competência), mesmo antes de o dinheiro entrar/sair. Ex.: 13º provisionado mês a mês.", rota: "/fechamento" },
  { id: "dso", termos: /\bdso\b|prazo m[ée]dio de recebiment|days sales outstanding|dias (para|pra) receber/, titulo: "Prazo médio de recebimento (DSO)", texto: "Quantos dias, em média, seus clientes levam para pagar em relação ao vencimento. Quanto menor, mais rápido o dinheiro entra no caixa. O all4pay mede pelo atraso médio dos títulos já liquidados e pelo % pago no prazo.", rota: "/inadimplencia" },
  { id: "dpo", termos: /\bdpo\b|prazo m[ée]dio de pagament|days payable outstanding/, titulo: "Prazo médio de pagamento (DPO)", texto: "Quantos dias, em média, você leva para pagar seus fornecedores em relação ao vencimento. Alongar sem gerar multa/juros preserva capital de giro; atrasar demais arranha o relacionamento.", rota: "/pagamentos" },
  { id: "ciclo-caixa", termos: /ciclo (de caixa|financeiro|operacional)|cash conversion|convers[ãa]o de caixa/, titulo: "Ciclo de caixa", texto: "O tempo entre pagar fornecedores e receber dos clientes (aprox. DSO + prazo de estoque − DPO). Quanto maior o ciclo, mais capital de giro a operação exige para não faltar caixa no meio do caminho.", rota: "/fluxo-caixa" },
  { id: "margem-bruta", termos: /margem bruta|lucro bruto/, titulo: "Margem bruta", texto: "Receita − CMV (custo do que foi vendido), dividido pela receita. Mostra quanto sobra de cada venda antes das despesas operacionais. É o teto da sua lucratividade.", rota: "/dre" },
  { id: "margem-liquida", termos: /margem l[íi]quida|lucro l[íi]quido|margem final/, titulo: "Margem líquida", texto: "Lucro líquido ÷ receita — o que de fato sobra depois de TUDO (impostos, despesas, financeiro). É o termômetro final de rentabilidade do negócio.", rota: "/dre" },
  { id: "cmv", termos: /\bcmv\b|custo (da |de )?mercadoria|custo dos produtos|\bcogs\b|custo variável/, titulo: "CMV / Custo variável", texto: "Custo direto do que foi vendido (mercadoria, matéria-prima, taxas por venda). Varia com o volume. Receita − CMV = lucro bruto.", rota: "/dre" },
  { id: "opex", termos: /\bopex\b|despesa(s)? operacion|custo fixo|despesa fixa/, titulo: "OPEX / Despesas operacionais", texto: "As despesas de manter a operação de pé (folha, aluguel, softwares, marketing) — não variam diretamente com cada venda. Entram depois do lucro bruto no DRE.", rota: "/dre" },
  { id: "reserva", termos: /reserva (de caixa|de emerg[êe]ncia|financeira)|caixa m[íi]nimo|colch[ãa]o (de caixa|financeiro)/, titulo: "Reserva de caixa", texto: "Um caixa mínimo guardado para meses ruins — em geral 3 a 6 meses de custos fixos. O all4pay usa ~3 meses de operação ao avaliar se você pode gastar um valor.", rota: "/fluxo-caixa" },
  { id: "roi", termos: /\broi\b|retorno sobre (o )?investiment|retorno do investiment/, titulo: "ROI (retorno sobre investimento)", texto: "Ganho gerado ÷ valor investido. Mede se um investimento (marketing, equipamento, contratação) se paga e em quanto. ROI positivo = retornou mais do que custou.", rota: "/inteligencia" },
  { id: "sazonalidade", termos: /sazonalidade|sazonal|[ée]poca do ano|meses (fortes|fracos)|pico de venda/, titulo: "Sazonalidade", texto: "A variação previsível da receita ao longo do ano (datas fortes, meses fracos). O all4pay detecta seus padrões sazonais para projetar caixa e antecipar apertos.", rota: "/inteligencia" },
  { id: "ticket-medio", termos: /ticket m[ée]dio|valor m[ée]dio (por|da) (venda|pedido|compra)|ticket/, titulo: "Ticket médio", texto: "O valor médio de cada venda: receita ÷ número de vendas no período. Subir o ticket (upsell, combos) cresce a receita sem precisar de mais clientes.", rota: "/painel-vendas" },
  { id: "payback", termos: /payback|tempo de retorno|em quanto tempo (se paga|recupero)|prazo de retorno/, titulo: "Payback", texto: "O tempo até um investimento se pagar com o retorno que gera (valor investido ÷ ganho mensal). Payback curto = capital de volta rápido para reinvestir.", rota: "/inteligencia" },
  { id: "antecipacao", termos: /antecipa[çc][ãa]o de receb|antecipar (os )?receb|adiantamento de receb|antecipar (a )?venda|desconto de duplicata/, titulo: "Antecipação de recebíveis", texto: "Receber hoje um valor que só cairia no futuro (vendas a prazo/cartão/boleto), pagando uma taxa de desconto. Melhora o caixa imediato ao custo de abrir mão de parte do valor — útil para cobrir um aperto sem tomar dívida.", rota: "/recebiveis" },
  { id: "markup", termos: /markup|marca[çc][ãa]o (de pre[çc]o|sobre custo)|remarca[çc][ãa]o/, titulo: "Markup", texto: "Quanto você soma ao custo para formar o preço de venda (ex.: custo R$100 com markup 2x → preço R$200). Diferente de margem, que é medida SOBRE o preço final, não sobre o custo.", rota: "/painel-vendas" },
  { id: "lucro-operacional", termos: /lucro operacional|resultado operacional|\bebit\b/, titulo: "Lucro operacional (EBIT)", texto: "O lucro gerado pela operação antes de juros e imposto de renda, mas já depois da depreciação. No DRE: EBITDA − depreciação/amortização. Mede a eficiência da operação em si.", rota: "/dre" },
  { id: "depreciacao", termos: /deprecia[çc][ãa]o|amortiza[çc][ãa]o|desgaste do ativo/, titulo: "Depreciação / Amortização", texto: "A perda de valor de um bem ao longo do tempo (máquina, veículo, software), lançada como despesa contábil SEM saída de caixa. Reduz o lucro no DRE, mas não o caixa — por isso o EBITDA a exclui.", rota: "/dre" },
  { id: "wacc", termos: /\bwacc\b|custo (m[ée]dio )?(ponderado )?de capital|custo de capital/, titulo: "WACC (custo de capital)", texto: "O custo médio ponderado do capital da empresa (dívida + capital próprio). É a taxa mínima que um investimento precisa render para criar valor em vez de destruir.", rota: "/inteligencia" },
  { id: "arr", termos: /\barr\b|receita recorrente anual|recorrente anual|annual recurring/, titulo: "ARR (receita recorrente anual)", texto: "A receita recorrente anualizada: MRR × 12. Projeta quanto os contratos/assinaturas ativos rendem em um ano se nada mudar. É a leitura anual do MRR.", rota: "/recorrencias" },
  { id: "prolabore", termos: /pr[óo]-?labore|retirada do (s[óo]cio|dono)|sal[áa]rio do (dono|s[óo]cio)/, titulo: "Pró-labore", texto: "A remuneração mensal dos sócios pelo trabalho na empresa (diferente de distribuição de lucro). Entra como despesa de folha no DRE e sai do caixa todo mês.", rota: "/dre" },
  { id: "regime-trib", termos: /regime tribut[áa]ri|simples nacional|lucro presumido|lucro real|tributa[çc][ãa]o da empresa/, titulo: "Regime tributário", texto: "O modelo de tributação da empresa (Simples Nacional, Lucro Presumido ou Real) que define quais impostos e alíquotas incidem sobre a receita. Impacta direto os impostos no DRE.", rota: "/dre" },
  { id: "juros-mora", termos: /juros de mora|multa (por|de) atraso|encargo(s)? de atraso|\bmora\b/, titulo: "Juros de mora / multa por atraso", texto: "O acréscimo cobrado quando um título é pago após o vencimento: multa (percentual fixo) + juros de mora (por dia de atraso). Aumenta o que você recebe de um cliente atrasado — ou o que paga a um fornecedor.", rota: "/inadimplencia" },
  { id: "aliquota-efetiva", termos: /al[íi]quota efetiv|al[íi]quota real|imposto efetivo/, titulo: "Alíquota efetiva", texto: "No Simples Nacional, o que você paga NÃO é a alíquota da tabela (nominal). A efetiva é (RBT12 × nominal − parcela a deduzir) ÷ RBT12: começa menor e sobe suave dentro da faixa. É a alíquota que realmente pesa sobre a receita.", rota: "/dre" },
  { id: "rbt12", termos: /\brbt12\b|rbt 12|receita bruta (dos )?[úu]ltimos 12|faturamento (dos )?[úu]ltimos 12 meses/, titulo: "RBT12 (receita bruta 12 meses)", texto: "A Receita Bruta Total dos últimos 12 meses. É a base que define a FAIXA e a alíquota efetiva do Simples Nacional. Quando passa de R$4,8 milhões, a empresa se desenquadra do Simples e migra para Lucro Presumido/Real.", rota: "/dre" },
  { id: "taxa-gateway", termos: /taxa de (gateway|adquirente|cart[ãa]o|maquininha)|\bspread\b|\bmdr\b|taxa da m[áa]quina/, titulo: "Taxa de gateway / MDR", texto: "O percentual que a adquirente/gateway retém de cada venda no cartão (MDR). Reduz o valor líquido que cai na conta — é um custo variável que abate da receita.", rota: "/painel-vendas" },
  { id: "balanco", termos: /balan[çc]o patrimonial|balan[çc]o cont[áa]bil/, titulo: "Balanço patrimonial", texto: "A foto do patrimônio num instante: Ativo (o que a empresa tem/recebe) = Passivo (o que deve) + Patrimônio Líquido (capital dos sócios). Complementa o DRE (que é um filme do período).", rota: "/razao" },
  { id: "ativo-passivo", termos: /ativo circulante|passivo circulante|ativo e passivo|o que [ée] (o )?(ativo|passivo)(?! imobiliz)/, titulo: "Ativo × Passivo (circulante)", texto: "Ativo circulante = recursos de curto prazo (caixa, a receber, estoque). Passivo circulante = obrigações de curto prazo (a pagar, empréstimos, impostos). A relação entre eles é a liquidez corrente.", rota: "/inteligencia" },
  { id: "patrimonio", termos: /patrim[ôóo]nio l[íi]quido|capital pr[óo]prio|\bequity\b/, titulo: "Patrimônio líquido", texto: "O que sobra para os sócios depois de descontar tudo que a empresa deve (Ativo − Passivo). É o capital próprio acumulado — cresce com lucro retido, cai com prejuízo e distribuição.", rota: "/razao" },
  { id: "roe", termos: /\broe\b|retorno sobre (o )?(patrim[ôóo]nio|capital pr[óo]prio|equity)/, titulo: "ROE (retorno sobre patrimônio)", texto: "Lucro líquido ÷ patrimônio líquido. Mede quanto de lucro a empresa gera sobre o capital dos sócios — a rentabilidade do dinheiro investido no negócio.", rota: "/inteligencia" },
  { id: "roic", termos: /\broic\b|retorno sobre (o )?capital investido/, titulo: "ROIC (retorno sobre capital investido)", texto: "O retorno operacional sobre o capital total empregado (próprio + dívida). Acima do WACC, a operação cria valor; abaixo, destrói. Aqui é aproximado por resultado anualizado ÷ capital empregado.", rota: "/inteligencia" },
  { id: "alavancagem", termos: /alavancagem|endividament|d[íi]vida l[íi]quida|grau de endivid/, titulo: "Alavancagem / Endividamento", texto: "O quanto a empresa se financia com dívida em vez de capital próprio. Medida comum: Dívida líquida ÷ EBITDA. Alavancagem alta amplia ganhos e perdas — e o risco de caixa se a receita cair.", rota: "/inteligencia" },
  { id: "liquidez-seca", termos: /liquidez seca|quick ratio|liquidez imediata/, titulo: "Liquidez seca", texto: "Como a liquidez corrente, mas tirando o estoque (o ativo mais difícil de virar dinheiro): (ativo circulante − estoque) ÷ passivo circulante. Um teste mais duro de cobertura das contas de curto prazo.", rota: "/inteligencia" },
  { id: "split-pag", termos: /split de pagament|divis[ãa]o de recebiment|marketplace split/, titulo: "Split de pagamento", texto: "Divide automaticamente o valor de uma venda entre partes (ex.: plataforma e vendedor) no momento do pagamento. Cada parte recebe sua fatia direto, sem repasse manual.", rota: "/recebimentos" },
  { id: "danfe", termos: /\bdanfe\b|nf-?e\b|nota fiscal eletr[óo]nica de produto/, titulo: "DANFE / NF-e", texto: "O documento auxiliar da Nota Fiscal eletrônica de produto (mercadoria). Acompanha a mercadoria e comprova a operação; no all4pay a venda é o documento-mãe que gera recebível, imposto e nota.", rota: "/notas-fiscais" },
  { id: "retencao", termos: /reten[çc][ãa]o de imposto|imposto retido|\biss\b|\birrf\b|inss retido|retido na fonte/, titulo: "Retenção de imposto (ISS/IRRF)", texto: "Parte do imposto que o pagador retém e recolhe no lugar do prestador (ex.: ISS, IRRF sobre serviços). Reduz o valor líquido recebido, mas é imposto adiantado — aparece como dedução da receita.", rota: "/dre" },
  { id: "distrib-lucro", termos: /distribui[çc][ãa]o de lucro|dividendo|lucro distribu[íi]|retirada de lucro/, titulo: "Distribuição de lucros", texto: "A parte do lucro repassada aos sócios (isenta de IR na pessoa física, diferente do pró-labore). Sai do caixa e reduz o patrimônio líquido — só distribua o que não compromete o capital de giro e a reserva.", rota: "/dre" },
  { id: "encargos", termos: /13[ºo]|d[ée]cimo terceiro|f[ée]rias|encargos trabalhist|\bfgts\b|custo de folha/, titulo: "Encargos trabalhistas (13º, férias, FGTS)", texto: "Os custos sobre a folha além do salário: 13º, férias (+1/3), FGTS (8%), INSS patronal. Provisione mês a mês (competência) para não tomar um susto de caixa em dezembro/nas férias.", rota: "/dre" },
  { id: "comissao", termos: /comiss[ãa]o de venda|comiss[ãa]o (do|de) vendedor|percentual de comiss/, titulo: "Comissão de vendas", texto: "O percentual pago ao vendedor sobre o que vende. É um custo variável (varia com a receita) — entra na margem de contribuição, não nas despesas fixas.", rota: "/painel-vendas" },
  { id: "margem-op", termos: /margem operacional|margem ebit\b/, titulo: "Margem operacional", texto: "Lucro operacional (EBIT) ÷ receita. Mostra quanto sobra da operação em si, antes de juros e imposto de renda — a eficiência do negócio depois de todas as despesas operacionais.", rota: "/dre" },
  { id: "receita-liquida", termos: /receita l[íi]quida|faturamento l[íi]quido|receita ap[óo]s imposto/, titulo: "Receita líquida", texto: "Receita bruta − impostos sobre a venda (e devoluções/abatimentos). É a base real sobre a qual se calculam as margens no DRE — o que de fato entra antes dos custos.", rota: "/dre" },
  { id: "tir-vpl", termos: /\btir\b|\bvpl\b|taxa interna de retorno|valor presente l[íi]quido|fluxo de caixa descontado|\bdcf\b/, titulo: "TIR / VPL", texto: "Ferramentas para avaliar investimentos trazendo fluxos futuros a valor presente. VPL = valor de hoje dos fluxos menos o investimento (positivo cria valor). TIR = a taxa que zera o VPL; compare-a ao seu custo de capital (WACC).", rota: "/inteligencia" },
  { id: "orcamento", termos: /or[çc]amento|\bbudget\b|planejamento or[çc]ament|\bforecast\b|previs[ãa]o or[çc]ament/, titulo: "Orçamento / Forecast", texto: "O plano de receitas e despesas para o período à frente. Comparado ao realizado, mede a acurácia e revela desvios cedo. O forecast é a reprojeção do orçamento conforme o ano anda.", rota: "/orcamento" },
  { id: "custo-oport", termos: /custo de oportunidade/, titulo: "Custo de oportunidade", texto: "O retorno que você abre mão ao escolher uma opção em vez da melhor alternativa. Ex.: deixar caixa parado tem o custo de oportunidade do que ele renderia aplicado ou reinvestido.", rota: "/inteligencia" },
  { id: "fatura-cartao", termos: /fatura de cart[ãa]o|fatura do cart[ãa]o|antecipa[çc][ãa]o de cart[ãa]o|receb[íi]vel de cart[ãa]o|repasse (da |do )?(adquirente|cart[ãa]o)/, titulo: "Recebível de cartão", texto: "As vendas no cartão viram recebíveis que a adquirente repassa depois (à vista em ~30 dias, ou parcela a parcela). Cada parcela é uma entrada prevista no fluxo até cair — e pode ser antecipada pagando uma taxa.", rota: "/recebiveis" },
  { id: "meta-vendas", termos: /meta de venda|meta de faturament|meta comercial|atingimento de meta|bati (a )?meta/, titulo: "Meta de vendas", texto: "O objetivo de faturamento do período. O atingimento (realizado ÷ meta) mostra se o comercial está no ritmo — e alimenta a projeção de caixa e o cálculo de comissões.", rota: "/painel-vendas" },
  { id: "ted-doc", termos: /\bted\b|\bdoc\b|transfer[êe]ncia banc[áa]ria/, titulo: "TED / DOC", texto: "Transferências entre bancos. A TED cai no mesmo dia (acima de certo valor); o DOC (em desuso) compensava no dia seguinte. Hoje o Pix substitui ambos na maioria dos casos, sem tarifa e instantâneo.", rota: "/movimentacoes" },
  { id: "open-finance", termos: /open finance|open banking|conex[ãa]o banc[áa]ria autom/, titulo: "Open Finance", texto: "O compartilhamento autorizado dos seus dados bancários entre instituições. No all4pay, conecta suas contas para importar extratos e saldos automaticamente, sem enviar OFX na mão.", rota: "/upload" },
  { id: "conta-tipos", termos: /conta corrente|conta digital|conta escrow|conta de custódia|conta banc[áa]ria/, titulo: "Tipos de conta", texto: "Conta corrente/digital é onde o dinheiro circula no dia a dia. Conta escrow (custódia) retém um valor até uma condição ser cumprida (garantia). No all4pay cada conta tem saldo próprio consolidado no caixa.", rota: "/contas" },
  { id: "adquirente", termos: /adquirente|subadquirente|credenciadora|maquininha|\bpsp\b|gateway de pagament/, titulo: "Adquirente / Gateway (PSP)", texto: "A empresa que processa o pagamento no cartão e repassa o dinheiro para você (Cielo, Stone, PagSeguro…). Cobra o MDR por transação e define o prazo de repasse (D+1, D+30). O gateway/PSP é a camada técnica que conecta sua loja a ela.", rota: "/painel-vendas" },
  { id: "liquidacao", termos: /liquida[çc][ãa]o financeira|\bd\+\d+\b|prazo de repasse|prazo de liquida[çc]/, titulo: "Liquidação / D+N", texto: "O prazo até o dinheiro de uma venda cair na conta. D+1 = um dia útil após a venda; D+30 = trinta dias (comum em cartão à vista). Antecipar reduz o prazo pagando uma taxa. O all4pay projeta esses recebíveis no fluxo.", rota: "/conciliacao-bancaria" },
  { id: "capex", termos: /\bcapex\b|investimento em (ativo|imobilizado)|gasto de capital/, titulo: "CAPEX", texto: "Gasto de capital: investimento em ativos de longo prazo (máquinas, obras, equipamentos) que se deprecia ao longo do tempo. Diferente do OPEX (despesa recorrente da operação). Não abate o EBITDA direto — vira depreciação.", rota: "/inteligencia" },
  { id: "receita-diferida", termos: /receita diferida|receita antecipada|receita a apropriar|deferred revenue/, titulo: "Receita diferida", texto: "Dinheiro já recebido por um serviço/assinatura ainda NÃO entregue — é passivo até ser reconhecido pela competência (ex.: plano anual pago à vista, reconhecido 1/12 por mês). Base do reconhecimento de receita (IFRS 15).", rota: "/receita" },
  { id: "mei-das", termos: /\bmei\b|microempreendedor|\bdas\b|documento de arrecada[çc]/, titulo: "MEI / DAS", texto: "MEI é o regime do microempreendedor individual, com faturamento limitado e tributação simplificada. O DAS é a guia mensal única que recolhe os impostos do Simples/MEI. No DRE entra como imposto sobre a receita.", rota: "/dre" },
  { id: "nfce-cte", termos: /nfc-?e|cupom fiscal|\bct-?e\b|conhecimento de transporte|nf de servi/, titulo: "NFC-e / CT-e", texto: "Documentos fiscais eletrônicos: a NFC-e é o cupom fiscal do varejo (venda ao consumidor); o CT-e cobre transporte de carga. Como toda nota, a venda é o documento-mãe que propaga para recebível e imposto.", rota: "/notas-fiscais" },
  { id: "substituicao-trib", termos: /substitui[çc][ãa]o tribut[áa]ria|\bst\b icms|imposto antecipado na cadeia/, titulo: "Substituição tributária (ST)", texto: "Regime em que um elo da cadeia (indústria/importador) recolhe o ICMS de toda a cadeia antecipadamente. Muda como o imposto aparece na sua compra/venda — é destacado à parte no custo.", rota: "/dre" },
  { id: "credito-trib", termos: /cr[ée]dito tribut[áa]rio|cr[ée]dito de (icms|pis|cofins)|imposto a recuperar/, titulo: "Crédito tributário", texto: "Imposto pago na compra de insumos que você pode abater do imposto devido na venda (não-cumulatividade de ICMS/PIS/COFINS). Reduz o imposto líquido a recolher — um ativo a recuperar.", rota: "/dre" },
  { id: "duplicata", termos: /duplicata|t[íi]tulo de cobran[çc]a|nota de d[ée]bito/, titulo: "Duplicata", texto: "Título de crédito emitido a partir de uma venda a prazo — a promessa de pagamento do cliente. Pode ser cobrada, protestada ou antecipada (descontada) no banco para virar caixa antes do vencimento.", rota: "/recebiveis" },
  { id: "factoring", termos: /factoring|fomento mercantil|venda de receb[íi]vel|desconto de t[íi]tulo/, titulo: "Factoring / Antecipação", texto: "Vender seus recebíveis (duplicatas) a uma empresa de fomento por um valor à vista menor, para gerar caixa imediato. Parecido com antecipação de recebíveis — troca prazo por liquidez, ao custo de uma taxa de deságio.", rota: "/recebiveis" },
  { id: "hedge-cambio", termos: /\bhedge\b|prote[çc][ãa]o cambial|\bc[âa]mbio\b|risco cambial|varia[çc][ãa]o cambial/, titulo: "Hedge / Câmbio", texto: "Câmbio é a conversão entre moedas (compras/vendas em dólar, etc.). Hedge é a proteção contra a variação cambial (trava o preço futuro) para o resultado não depender do sobe-e-desce da moeda.", rota: "/inteligencia" },
  { id: "nrr", termos: /net revenue retention|\bnrr\b|reten[çc][ãa]o de receita|expans[ãa]o de receita/, titulo: "Net Revenue Retention (NRR)", texto: "Quanto da receita recorrente de uma safra de clientes você mantém e expande ao longo do tempo, líquido de churn. Acima de 100% significa que upsell/expansão superam os cancelamentos — crescimento mesmo sem novos clientes.", rota: "/recorrencias" },
  { id: "lucratividade", termos: /margem de lucro|lucratividade|rentabilidade|quanto (sobra|lucro) de cada|percentual de lucro/, titulo: "Lucratividade × Rentabilidade", texto: "Lucratividade = lucro ÷ receita (quanto sobra de cada venda — a margem). Rentabilidade = lucro ÷ capital investido (o retorno sobre o dinheiro aplicado, como o ROE). Uma mede a operação; a outra, o investimento.", rota: "/dre" },
  { id: "solvencia", termos: /solv[êe]ncia|capacidade de pagar as d[íi]vidas|solvente/, titulo: "Solvência", texto: "A capacidade da empresa de honrar TODAS as obrigações no longo prazo (ativos ≥ passivos), não só as de curto prazo (isso é liquidez). Insolvência crônica é o caminho para a falência.", rota: "/inteligencia" },
  { id: "dfc-indireto", termos: /\bdfc\b|demonstra[çc][ãa]o (do|de) fluxo de caixa|fluxo de caixa indireto|fluxo de caixa direto/, titulo: "DFC (Demonstração do Fluxo de Caixa)", texto: "O relatório que explica de onde veio e para onde foi o caixa no período, separado em operacional, investimento e financiamento. Método direto (entradas/saídas) ou indireto (a partir do lucro). Complementa o DRE.", rota: "/fluxo-caixa" },
  { id: "estoque", termos: /ponto de reposi[çc][ãa]o|estoque m[íi]nimo|giro de estoque|curva abc|cobertura de estoque/, titulo: "Gestão de estoque (ponto de reposição, curva ABC)", texto: "Ponto de reposição = o nível de estoque em que você recompra (consumo × prazo de entrega + estoque mínimo de segurança). Giro de estoque = quantas vezes ele se renova no período. Curva ABC prioriza os itens que mais pesam no valor.", rota: "/inteligencia" },
  { id: "promissoria", termos: /nota promiss[óo]ria|promiss[óo]ria/, titulo: "Nota promissória", texto: "Uma promessa de pagamento por escrito: o emitente se compromete a pagar um valor numa data. Diferente da duplicata (que nasce de uma venda), a promissória é um compromisso direto de dívida.", rota: "/pagamentos" },
  { id: "cheque-especial", termos: /cheque especial|limite da conta|conta garantida/, titulo: "Cheque especial", texto: "Um limite de crédito pré-aprovado na conta para cobrir saldo negativo — dos créditos mais CAROS do mercado. Usar como caixa recorrente destrói a margem; sirva-se dele só para um aperto pontual e quite rápido.", rota: "/fluxo-caixa" },
  { id: "capital-terceiros", termos: /capital de terceiros|capital pr[óo]prio (vs|x) terceiros|fontes de financiament/, titulo: "Capital próprio × de terceiros", texto: "Capital próprio é o dinheiro dos sócios (patrimônio líquido); capital de terceiros é dívida (bancos, fornecedores). Financiar-se com dívida alavanca o retorno, mas aumenta o risco e o custo financeiro.", rota: "/inteligencia" },
  { id: "imobilizado", termos: /imobilizado|ativo imobilizado|bens (do|da) empresa|m[áa]quinas e equipament/, titulo: "Ativo imobilizado", texto: "Os bens de uso duradouro da empresa (máquinas, veículos, móveis, imóveis) que não são vendidos no dia a dia. Perdem valor pela depreciação e representam capital investido na operação.", rota: "/inteligencia" },
  { id: "carencia-parcelamento", termos: /car[êe]ncia|parcelament(o| da d[íi]vida)|renegocia[çc][ãa]o de d[íi]vida|amortiza[çc][ãa]o de d[íi]vida/, titulo: "Carência / Parcelamento", texto: "Carência é o período inicial em que você só paga juros (ou nada) antes de começar a amortizar o principal de um empréstimo. Parcelamento divide a dívida em prestações. Ambos aliviam o caixa no curto prazo ao custo de mais juros no total.", rota: "/pagamentos" },
  { id: "juros-compostos", termos: /juros compostos|juros sobre juros|juros simples/, titulo: "Juros compostos", texto: "Juros que incidem sobre o principal E sobre os juros já acumulados (\"juros sobre juros\") — crescem exponencialmente. É o que faz uma dívida rolada explodir e um investimento render no longo prazo. Juros simples incidem só sobre o principal.", rota: "/inteligencia" },
  { id: "selic-indexador", termos: /taxa selic|\bselic\b|\bcdi\b|indexador|corre[çc][ãa]o monet[áa]ria|\bipca\b|\bigpm\b/, titulo: "Selic / CDI / Indexadores", texto: "A Selic é a taxa básica de juros da economia; o CDI acompanha de perto e baliza rendimentos e empréstimos. Indexadores (IPCA, IGP-M) corrigem contratos/aluguéis pela inflação. Sobem o custo da dívida pós-fixada quando os juros sobem.", rota: "/inteligencia" },
  { id: "inflacao", termos: /\binfla[çc][ãa]o\b|perda do poder de compra|reajuste de pre[çc]o/, titulo: "Inflação", texto: "A alta geral dos preços, que corrói o poder de compra do seu caixa e encarece os custos. Preços parados em inflação alta significam margem caindo — reajuste e negocie prazos para não perder valor.", rota: "/inteligencia" },
  { id: "margem-seguranca", termos: /margem de seguran[çc]a|quanto posso cair|dist[âa]ncia do ponto de equil/, titulo: "Margem de segurança", texto: "O quanto a receita pode cair antes de você bater o ponto de equilíbrio e entrar no prejuízo: (receita − ponto de equilíbrio) ÷ receita. Quanto maior, mais folga para aguentar uma queda de vendas.", rota: "/dre" },
  { id: "geracao-caixa", termos: /gera[çc][ãa]o de caixa|geration de caixa|caixa gerado (pela|na) opera/, titulo: "Geração de caixa", texto: "Quanto de dinheiro a operação efetivamente PRODUZ no período (entradas realizadas − saídas realizadas). Positiva e consistente é o sinal de um negócio saudável; negativa persistente queima o caixa e encurta o runway.", rota: "/fluxo-caixa" },
  { id: "aporte-valuation", termos: /\baporte\b|rodada de investiment|\bvaluation\b|capta[çc][ãa]o|investidor|valor da empresa/, titulo: "Aporte / Valuation", texto: "Aporte é a entrada de capital dos sócios/investidores no caixa (não é receita — é financiamento). Valuation é quanto a empresa vale, base para definir a fatia (equity) que um investidor recebe numa rodada em troca do aporte.", rota: "/inteligencia" },
  { id: "amortizacao-sistema", termos: /tabela price|sistema (price|sac)|\bsac\b|sistema de amortiza|price (vs|x|ou) sac/, titulo: "Amortização: Price × SAC", texto: "Dois jeitos de quitar um empréstimo. Price: parcela FIXA do começo ao fim (mais simples de planejar, paga mais juros no total). SAC: amortização constante e parcela DECRESCENTE (começa mais alta, mas o total de juros é menor). Peça \"simular empréstimo de X em Nx a T% ao mês\" que eu calculo os dois.", rota: "/inteligencia" },
];

/** Detecta intenção CONCEITUAL ("o que é/como calcula/para que serve"). */
const CONCEITUAL = /\b(o que|oque|que [ée]|qual [ée]|como (calcul\w*|funciona|fazer)|para que serve|explic\w*|defin\w*|signific\w*|entender)\b/i;

/** Tenta responder pela base de conhecimento. Retorna a entrada ou null. */
export function buscarKB(q: string): KBEntry | null {
  const s = q.toLowerCase();
  const conceitual = CONCEITUAL.test(s);
  // Query com número (e não-conceitual) é CÁLCULO, não conceito — não deixa o
  // atalho de termo forte sombrear a calculadora do motor. Ex.: "quanto cobrar de
  // um boleto de 1000 vencido há 30 dias?" tem "boleto" (termo forte) mas é mora,
  // não o verbete "boleto"; "o que é boleto?" (conceitual) segue vindo à KB.
  const temNumero = /\d/.test(s);
  for (const e of KB) {
    if (e.termos.test(s)) {
      // termos fortes (sigla/numérico) respondem mesmo sem o gatilho conceitual.
      // Saem do fallback forte os que têm intent COMPUTADO no motor (número real):
      // concentração, ponto de equilíbrio, EBITDA, runway, burn, score, receita
      // líquida, carga tributária. Para esses, "qual meu X?" cai no motor (número);
      // só respondem como CONCEITO quando a pergunta é explicitamente conceitual.
      if (conceitual || (!temNumero && /ltv|cac|mrr|dre|aging|churn|\bnsu\b|\bdso\b|\bdpo\b|liquidez|capital de giro|compet[êe]ncia|boleto|\bpix\b|nfs-?e|partidas? (dobrada|dupla)|provis[ãa]o|accrual/i.test(s))) return e;
    }
  }
  return null;
}
